name: .net build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TestServer/TestServer.sln
    - name: Build TestServer
      run: dotnet build --no-restore TestServer/TestServer.csproj
    - name: Build TestServerTests
      run: dotnet build --no-restore TestServerTests/TestServerTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal TestServerTests/TestServerTests.csproj
